import { Request, Response, NextFunction } from 'express';
import { prisma } from '../utils/prisma';

export class TestController {
  static async insertTestData(req: Request, res: Response, next: NextFunction) {
    try {
      // 1. Detect if the table is "test-data" or "test_data"
      let tableName = '';
      const tables: any = await prisma.$queryRaw`
        SELECT table_name 
        FROM information_schema.tables 
        WHERE table_schema = 'public' 
          AND (table_name = 'test-data' OR table_name = 'test_data')
      `;

      if (tables && tables.length > 0) {
        tableName = tables[0].table_name;
      } else {
        // Get all tables in database for debugging
        const allTables: any = await prisma.$queryRaw`
          SELECT table_name 
          FROM information_schema.tables 
          WHERE table_schema = 'public'
        `;
        return res.status(404).json({
          success: false,
          message: 'Neither "test-data" nor "test_data" table was found in the database. Please ensure the table exists in your Supabase database.',
          availableTables: allTables.map((t: any) => t.table_name)
        });
      }

      // 2. Fetch the columns of the table
      const columns: any = await prisma.$queryRawUnsafe(`
        SELECT column_name, data_type, is_nullable
        FROM information_schema.columns
        WHERE table_name = '${tableName}' AND table_schema = 'public'
      `);

      // 3. Map request body to existing columns (excluding read-only/autogenerated like id, created_at, etc.)
      const inputData = req.body || {};
      const columnsToInsert: string[] = [];
      const valuesToInsert: any[] = [];
      const placeholders: string[] = [];

      let index = 1;
      for (const col of columns) {
        const colName = col.column_name;
        // Skip autogenerated system columns usually handled by Postgres
        if (colName === 'id' || colName === 'created_at' || colName === 'createdAt' || colName === 'updatedAt') {
          continue;
        }

        if (inputData[colName] !== undefined) {
          columnsToInsert.push(`"${colName}"`);
          valuesToInsert.push(inputData[colName]);
          placeholders.push(`$${index}`);
          index++;
        }
      }

      // 4. Handle default/fallback if no matching body fields are passed
      if (columnsToInsert.length === 0) {
        // Find first text/varchar/json/int column that is not 'id' or 'created_at'
        const writableCol = columns.find((col: any) => 
          col.column_name !== 'id' && 
          col.column_name !== 'created_at' && 
          col.column_name !== 'createdAt'
        );

        if (writableCol) {
          const colName = writableCol.column_name;
          columnsToInsert.push(`"${colName}"`);
          
          // Cast fallback depending on expected type
          const dataType = writableCol.data_type.toLowerCase();
          if (dataType.includes('int') || dataType.includes('dec') || dataType.includes('num')) {
            valuesToInsert.push(Math.floor(Math.random() * 1000));
          } else {
            valuesToInsert.push(`Dynamic Test Value - ${new Date().toISOString()}`);
          }
          
          placeholders.push('$1');
        } else {
          return res.status(400).json({
            success: false,
            message: 'No writable columns found in your table to insert dynamic data.',
            tableColumns: columns
          });
        }
      }

      // 5. Construct and execute the raw SQL INSERT
      const sql = `INSERT INTO "${tableName}" (${columnsToInsert.join(', ')}) VALUES (${placeholders.join(', ')}) RETURNING *`;
      const result: any = await prisma.$queryRawUnsafe(sql, ...valuesToInsert);

      res.status(201).json({
        success: true,
        message: 'Dynamic test data inserted successfully!',
        tableName,
        insertedRow: result,
        schema: columns
      });
    } catch (error: any) {
      next(error);
    }
  }
}
